--Create Database --
CREATE DATABASE salwa_fadillah;  
USE salwa_fadillah;

--Create Table Items --
CREATE TABLE public.items (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"cost" int4 NOT NULL,
	created_by varchar(255) NULL,
	created_datetime timestamp NULL,
	description varchar(500) NULL,
	"name" varchar(500) NOT NULL,
	price int4 NOT NULL,
	updated_by varchar(255) NULL,
	updated_datetime timestamp NULL,
	CONSTRAINT items_pkey PRIMARY KEY (id)
);

--Create Table po_d --
CREATE TABLE public.po_d (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_datetime timestamp NULL,
	item_cost int4 NOT NULL,
	item_price int4 NOT NULL,
	item_qty int4 NOT NULL,
	updated_by varchar(255) NULL,
	updated_datetime timestamp NULL,
	item_id int8 NOT NULL,
	poh_id int8 NOT NULL,
	CONSTRAINT po_d_pkey PRIMARY KEY (id),
	CONSTRAINT fkgcqrqy508t6l5mftxbiso93x0 FOREIGN KEY (poh_id) REFERENCES po_h(id),
	CONSTRAINT fkim2vsw2kobwppqqqfq1qbdg5u FOREIGN KEY (item_id) REFERENCES items(id)
);

--Create Table po_h --
CREATE TABLE public.po_h (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date_time timestamp NULL,
	date_time timestamp NULL,
	description varchar(255) NULL,
	total_cost int4 NULL,
	total_price int4 NULL,
	updated_by varchar(255) NULL,
	updated_date_time timestamp NULL,
	user_id int8 NULL,
	CONSTRAINT po_h_pkey PRIMARY KEY (id),
	CONSTRAINT fkq3w71v3ng6u246x8bdlqewgw2 FOREIGN KEY (user_id) REFERENCES users(id)
);

--Create Table Users --
CREATE TABLE public.users (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(255) NULL,
	first_name varchar(500) NOT NULL,
	last_name varchar(500) NOT NULL,
	phone varchar(255) NULL,
	created_by varchar(255) NULL,
	created_datetime timestamp NOT NULL,
	updated_by varchar(255) NULL,
	updated_datetime timestamp NOT NULL,
	"password" varchar(200) NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);



--data dummy items --
INSERT INTO public.items ("cost", created_by, created_datetime, description, "name", price, updated_by, updated_datetime)
VALUES
(5000, 'admin', NOW(), 'Pulpen tinta biru', 'Pulpen', 7500, 'admin', NOW()),
(12000, 'admin', NOW(), 'Buku tulis 40 lembar', 'Buku Tulis', 15000, 'admin', NOW()),
(80000, 'admin', NOW(), 'Tas sekolah anak', 'Tas Sekolah', 100000, 'admin', NOW()),
(300000, 'admin', NOW(), 'Sepatu olahraga ukuran 42', 'Sepatu Olahraga', 350000, 'admin', NOW()),
(2000, 'admin', NOW(), 'Penghapus putih kecil', 'Penghapus', 3000, 'admin', NOW());


--data dummy users--
INSERT INTO public.users (email, first_name, last_name, phone, created_by, created_datetime, updated_by, updated_datetime, "password")
VALUES 
('dika@example.com', 'dika', 'aditya', '08123456789', 'system', NOW(), 'system', NOW(), 'admin123');

--data dummy po_h--
INSERT INTO public.po_h (created_by, created_date_time, date_time, description, total_cost, total_price, updated_by, updated_date_time, user_id)
VALUES ('dikaaditya', NOW(), NOW(), 'Purchase Order ATK', 0, 0, 'dikaaditya', NOW(), 6);

--data dummy po_d--
INSERT INTO public.po_d (created_by, created_datetime, item_cost, item_price, item_qty, updated_by, updated_datetime, item_id, poh_id)
VALUES
('dikaaditya', NOW(), 5000, 7500, 10, '', NOW(), 4, 8),   -- 10 Pulpen
('dikaaditya', NOW(), 12000, 15000, 5, '', NOW(), 5, 8), -- 5 Buku Tulis
('dikaaditya', NOW(), 80000, 100000, 2, '', NOW(), 6, 8); -- 2 Tas Sekolah





